import type { NextPage } from 'next'
import Head from 'next/head'

import Sidebar from 'components/Sidebar/Sidebar'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Spotify - Web Player</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Sidebar />
        <section>center</section>
        <footer>bottom</footer>
      </main>
    </>
  )
}

export default Home
